---
kind: pipeline
type: docker
name: linux-s390x

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
- name: build
  pull: always
  image: rancher/hardened-build-base:v1.16.10b7
  failure: ignore
  commands:
  - make DRONE_TAG=${DRONE_TAG}
  volumes:
  - name: docker
    path: /var/run/docker.sock



volumes:
- name: docker
  host:
    path: /var/run/docker.sock
